[package]
name = "imnodes"
version = "0.2.0"
edition = "2018"
authors = ["Benedikt Mandelkow", "imnodes-rs contributors"]
description = "Rust bindings to https://github.com/Nelarius/imnodes"
license = "MIT/Apache-2.0"
categories = ["gui", "api-bindings"]
readme = "README.md"

[dependencies]
imnodes-sys = { version = "0.1.0", path = "imnodes-sys" }
bitflags = "1.0"
parking_lot = "0.11"
once_cell = "1.1"


[workspace]
members = [
    "imnodes-sys",
]
exclude = [
    "imnodes-sys-bindgen",
    "imnodes-examples",
    "imnodes-wgpu-examples",
]
