[package]
name = "imnodes-wgpu-examples"
version = "0.1.0"
authors = ["Benedikt Mandelkow <benedikt.mandelkow@rwth-aachen.de>", "imgui-wgpu contributors"]
edition = "2018"

[dependencies]
imnodes = { path = "../" }

wgpu = "0.10.2"
winit = "0.25.0"
futures = "0.3.17"
imgui = "0.8.0"
imgui-winit-support = "0.8.0"
imgui-wgpu = "0.17.1"
