[package]
name = "imnodes-wgpu-examples"
version = "0.1.0"
authors = ["Benedikt Mandelkow <benedikt.mandelkow@rwth-aachen.de>", "imgui-wgpu contributors"]
edition = "2021"

[dependencies]
imnodes = { path = "../" }

wgpu = "0.13.1"
winit = "0.26.1"
futures = "0.3.21"
imgui = "0.8.2"
imgui-winit-support = { version = "0.8.2", features = ["winit-26"] }
imgui-wgpu = "0.20.0"
