name: Tests
on: [push, pull_request]

jobs:
  test:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --verbose
